avoid aliasing printf arguments (#5)
Summary:
Pull Request resolved: https://github.com/facebookexternal/fbc_shared/pull/5

gcc8 warns about `sprintf(ret, "%s...", ret, ...)` construct since the
destination and source are the same pointer.

```
.../src/config_parser.c: In function
'get_config_opts_desc':
.../src/config_parser.c:373:9: error:
passing argument 1 to restrict-qualified parameter aliases with argument 3
[-Werror=restrict]
```

We don't need to recopy all of these bytes anyway, we can just remember
where in the buffer to concatenate items, so do that.

Reviewed By: nivnoach

Differential Revision: D13804106

fbshipit-source-id: 651e355830742297cf5f0b4f4ce5a91869a62a80